"""Pydantic data models for the state management layer.

All models use frozen=True to enforce immutability.

V5 Architecture:
- JSON-based state (no SQLite)
- Models: StateFile, ProjectMeta, TaskRecord, OutputFileRecord, DocumentationMeta
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Literal

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Status/Phase type aliases for clarity
# ---------------------------------------------------------------------------

ProjectStatus = Literal["pending", "indexing", "indexed", "failed"]
TaskStatus = Literal["pending", "in_progress", "complete", "failed", "skipped"]
CheckpointStatus = Literal["in_progress", "complete", "interrupted", "failed"]
AnalysisPhase = Literal[
    "indexing", "module_analysis", "cross_reference", "doc_generation"
]
DocNodeStatus = Literal["planned", "generated", "failed"]


# ---------------------------------------------------------------------------
# V2 Models (JSON-based state management)
# ---------------------------------------------------------------------------


class OutputFileRecord(BaseModel, frozen=True):
    """Record of an output file generated by an agent task."""

    path: str
    tokens_written: int | None = None
    status: Literal["pending", "complete", "failed"] = "pending"


class TaskRecord(BaseModel, frozen=True):
    """A single task in the V2 task manifest."""

    type: Literal["batch", "single", "split", "index"]
    status: TaskStatus = "pending"
    cone_ids: list[str] = Field(default_factory=list)
    estimated_tokens: int = 0
    output_files: list[OutputFileRecord] = Field(default_factory=list)
    split_subtasks: list[str] | None = None  # For split tasks only
    depends_on: list[str] | None = None  # For index task only
    started_at: datetime | None = None
    completed_at: datetime | None = None
    error: str | None = None


class ProjectMeta(BaseModel, frozen=True):
    """Project metadata in V2 state."""

    id: str
    root_path: str
    analyzed_at: datetime
    languages: list[str] = Field(default_factory=list)
    file_count: int = 0
    function_count: int = 0
    class_count: int = 0
    total_lines: int = 0
    total_chars: int = 0
    total_tokens: int = 0
    analysis_status: Literal["pending", "in_progress", "complete", "failed"] = "pending"


class DocumentationMeta(BaseModel, frozen=True):
    """Documentation generation metadata."""

    output_dir: str = ".codebase-docs/"
    index_written: bool = False
    overviews_written: int = 0
    details_written: int = 0
    snippets_written: int = 0
    total_planned: int = 0
    source_files_covered: list[str] = Field(default_factory=list)
    source_file_coverage_percent: float = 0.0
    total_tokens_written: int = 0


class StateFile(BaseModel, frozen=True):
    """V2 unified state file schema."""

    schema_version: str = "2.0"
    project: ProjectMeta
    analysis_files: dict[str, str] = Field(default_factory=dict)
    tasks: dict[str, TaskRecord] = Field(default_factory=dict)
    documentation: DocumentationMeta = Field(default_factory=DocumentationMeta)
    metadata: dict = Field(default_factory=dict)

