"""Public surface of the canonical ``cbe-ir/2`` contract."""

from src.ir.models import (
    Availability,
    CapabilityCell,
    ConsumerReceipt,
    EntityKind,
    EntityRef,
    EvidenceSpan,
    ReadReceipt,
    Relation,
    ResolutionMethod,
    ResolutionStatus,
    RunManifest,
    RunTerminalState,
    SemanticModule,
    SemanticTaskState,
    SemanticTier,
    SourceRevision,
    SourceUnit,
    SourceUnitState,
    Symbol,
    VerificationReceipt,
    VerificationStatus,
    VerifierVerdict,
    deterministic_entity_id,
    normalize_relative_path,
    normalize_repo_root,
)
from src.ir.schema import IR_PROTOCOL_ID, ir_schema, ir_schema_hash
from src.ir.serialization import (
    CanonicalSerializationError,
    canonical_bytes,
    canonical_hash,
    deserialize_model,
    serialize_model,
)

__all__ = [
    "IR_PROTOCOL_ID",
    "Availability",
    "CanonicalSerializationError",
    "CapabilityCell",
    "ConsumerReceipt",
    "EntityKind",
    "EntityRef",
    "EvidenceSpan",
    "ReadReceipt",
    "Relation",
    "ResolutionMethod",
    "ResolutionStatus",
    "RunManifest",
    "RunTerminalState",
    "SemanticModule",
    "SemanticTaskState",
    "SemanticTier",
    "SourceRevision",
    "SourceUnit",
    "SourceUnitState",
    "Symbol",
    "VerificationReceipt",
    "VerificationStatus",
    "VerifierVerdict",
    "canonical_bytes",
    "canonical_hash",
    "deserialize_model",
    "deterministic_entity_id",
    "ir_schema",
    "ir_schema_hash",
    "normalize_relative_path",
    "normalize_repo_root",
    "serialize_model",
]
